[package]
name = "netowiru"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
futures = "0.3"
tokio = { version = "1", features = ["full"] }
# tokio-websockets = "0.12.1"
yaml-rust2 = "0.10.4"
